# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/formsettingqV5806.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

#class Ui_settingDialog(object):
class Ui_settingDialog:
    def setupUi(self, settingDialog):
        settingDialog.setObjectName("settingDialog")
        settingDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        settingDialog.resize(444, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settingDialog.sizePolicy().hasHeightForWidth())
        settingDialog.setSizePolicy(sizePolicy)
        settingDialog.setMinimumSize(QtCore.QSize(444, 300))
        settingDialog.setMaximumSize(QtCore.QSize(444, 300))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        settingDialog.setFont(font)
        settingDialog.setWindowTitle("Setting")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/bwsetting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settingDialog.setWindowIcon(icon)
        settingDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(settingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(116, 247, 320, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.charSetsBox = QtWidgets.QGroupBox(settingDialog)
        self.charSetsBox.setGeometry(QtCore.QRect(3, 10, 241, 269))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.charSetsBox.setFont(font)
        self.charSetsBox.setTitle("Changing the character set")
        self.charSetsBox.setObjectName("charSetsBox")
        self.latcharsButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.latcharsButton.setGeometry(QtCore.QRect(11, 36, 97, 27))
        self.latcharsButton.setText("&Lat")
        self.latcharsButton.setShortcut("")
        self.latcharsButton.setProperty("Tag", 0)
        self.latcharsButton.setObjectName("latcharsButton")
        self.numberButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.numberButton.setGeometry(QtCore.QRect(11, 74, 91, 27))
        self.numberButton.setText("&Number")
        self.numberButton.setShortcut("")
        self.numberButton.setProperty("Tag", 1)
        self.numberButton.setObjectName("numberButton")
        self.ruscharsButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.ruscharsButton.setGeometry(QtCore.QRect(11, 112, 101, 27))
        self.ruscharsButton.setText("&Rus")
        self.ruscharsButton.setShortcut("")
        self.ruscharsButton.setProperty("Tag", 2)
        self.ruscharsButton.setObjectName("ruscharsButton")
        self.callsignsButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.callsignsButton.setGeometry(QtCore.QRect(11, 150, 95, 27))
        self.callsignsButton.setText("&Callsigns")
        self.callsignsButton.setShortcut("")
        self.callsignsButton.setProperty("Tag", 3)
        self.callsignsButton.setObjectName("callsignsButton")
        self.usercharsButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.usercharsButton.setGeometry(QtCore.QRect(11, 188, 63, 27))
        self.usercharsButton.setText("&User")
        self.usercharsButton.setShortcut("")
        self.usercharsButton.setProperty("Tag", 4)
        self.usercharsButton.setObjectName("usercharsButton")
        self.userText = QtWidgets.QPlainTextEdit(self.charSetsBox)
        self.userText.setGeometry(QtCore.QRect(80, 182, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.userText.setFont(font)
        self.userText.setObjectName("userText")
        self.fileButton = QtWidgets.QRadioButton(self.charSetsBox)
        self.fileButton.setGeometry(QtCore.QRect(11, 235, 82, 17))
        self.fileButton.setText("&File")
        self.fileButton.setShortcut("")
        self.fileButton.setProperty("Tag", 5)
        self.fileButton.setObjectName("fileButton")
        self.minCharsBox = QtWidgets.QSpinBox(settingDialog)
        self.minCharsBox.setGeometry(QtCore.QRect(256, 16, 73, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.minCharsBox.setFont(font)
        self.minCharsBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minCharsBox.setSuffix("")
        self.minCharsBox.setPrefix("")
        self.minCharsBox.setMinimum(2)
        self.minCharsBox.setMaximum(7)
        self.minCharsBox.setProperty("value", 5)
        self.minCharsBox.setObjectName("minCharsBox")
        self.maxCharsBox = QtWidgets.QSpinBox(settingDialog)
        self.maxCharsBox.setGeometry(QtCore.QRect(256, 61, 73, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.maxCharsBox.setFont(font)
        self.maxCharsBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxCharsBox.setSuffix("")
        self.maxCharsBox.setPrefix("")
        self.maxCharsBox.setMinimum(2)
        self.maxCharsBox.setMaximum(7)
        self.maxCharsBox.setProperty("value", 5)
        self.maxCharsBox.setObjectName("maxCharsBox")
        self.groupsBox = QtWidgets.QSpinBox(settingDialog)
        self.groupsBox.setGeometry(QtCore.QRect(256, 106, 73, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupsBox.setFont(font)
        self.groupsBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupsBox.setSuffix("")
        self.groupsBox.setPrefix("")
        self.groupsBox.setMinimum(5)
        self.groupsBox.setMaximum(600)
        self.groupsBox.setSingleStep(5)
        self.groupsBox.setProperty("value", 60)
        self.groupsBox.setObjectName("groupsBox")
        self.speedBox = QtWidgets.QSpinBox(settingDialog)
        self.speedBox.setGeometry(QtCore.QRect(256, 151, 73, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.speedBox.setFont(font)
        self.speedBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedBox.setSuffix("")
        self.speedBox.setPrefix("")
        self.speedBox.setMinimum(5)
        self.speedBox.setMaximum(300)
        self.speedBox.setProperty("value", 12)
        self.speedBox.setObjectName("speedBox")
        self.toneBox = QtWidgets.QSpinBox(settingDialog)
        self.toneBox.setGeometry(QtCore.QRect(256, 196, 73, 37))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.toneBox.setFont(font)
        self.toneBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.toneBox.setSuffix("")
        self.toneBox.setPrefix("")
        self.toneBox.setMinimum(500)
        self.toneBox.setMaximum(2000)
        self.toneBox.setProperty("value", 700)
        self.toneBox.setObjectName("toneBox")
        self.label = QtWidgets.QLabel(settingDialog)
        self.label.setGeometry(QtCore.QRect(340, 23, 74, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setText("Min chars")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(settingDialog)
        self.label_2.setGeometry(QtCore.QRect(340, 68, 77, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setText("Max chars")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(settingDialog)
        self.label_3.setGeometry(QtCore.QRect(340, 114, 55, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setText("Groups")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(settingDialog)
        self.label_4.setGeometry(QtCore.QRect(340, 158, 98, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setText("Speed (wpm)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(settingDialog)
        self.label_5.setGeometry(QtCore.QRect(340, 200, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setText("Tone (Hz)")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(settingDialog)
        self.buttonBox.accepted.connect(settingDialog.accept)
        self.buttonBox.rejected.connect(settingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settingDialog)

    def retranslateUi(self, settingDialog):
        pass


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     settingDialog = QtWidgets.QDialog()
#     ui = Ui_settingDialog()
#     ui.setupUi(settingDialog)
#     settingDialog.show()
#     sys.exit(app.exec_())


