# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/mainformSL5806.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm:
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(850, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        MainForm.setMinimumSize(QtCore.QSize(850, 460))
        MainForm.setMaximumSize(QtCore.QSize(850, 460))
        MainForm.setWindowTitle("Morse Trainer by RD0D")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/cwkey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainForm.setWindowIcon(icon)
        MainForm.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.outputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputText.setGeometry(QtCore.QRect(0, 0, 849, 389))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputText.sizePolicy().hasHeightForWidth())
        self.outputText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputText.setFont(font)
        self.outputText.setLineWidth(1)
        self.outputText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.outputText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.outputText.setDocumentTitle("")
        self.outputText.setReadOnly(True)
        self.outputText.setPlainText("")
        self.outputText.setPlaceholderText("")
        self.outputText.setObjectName("outputText")
        MainForm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainForm)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainForm)
        self.toolBar.setWindowTitle("toolBar")
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNewText = QtWidgets.QAction(MainForm)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/bwplus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewText.setIcon(icon1)
        self.actionNewText.setText("New Text")
        self.actionNewText.setIconText("New Text")
        self.actionNewText.setToolTip("New Text (Alt + N)")
        self.actionNewText.setStatusTip("")
        self.actionNewText.setWhatsThis("")
        self.actionNewText.setShortcut("Alt+N")
        self.actionNewText.setObjectName("actionNewText")
        self.actionStart = QtWidgets.QAction(MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/bwplay.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon2)
        self.actionStart.setText("Start")
        self.actionStart.setIconText("Start")
        self.actionStart.setToolTip("Start (Alt + P)")
        self.actionStart.setShortcut("Alt+P")
        self.actionStart.setObjectName("actionStart")
        self.actionSetting = QtWidgets.QAction(MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/bwsetting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon3)
        self.actionSetting.setText("Setting")
        self.actionSetting.setIconText("Setting")
        self.actionSetting.setToolTip("Setting (Alt+ S)")
        self.actionSetting.setShortcut("Alt+S")
        self.actionSetting.setObjectName("actionSetting")
        self.actionAbout = QtWidgets.QAction(MainForm)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/bwquestion.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setText("About")
        self.actionAbout.setIconText("About")
        self.actionAbout.setToolTip("About (Alt + A)")
        self.actionAbout.setShortcut("Alt+A")
        self.actionAbout.setObjectName("actionAbout")
        self.actionExitApp = QtWidgets.QAction(MainForm)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/bwexit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExitApp.setIcon(icon5)
        self.actionExitApp.setText("Exit")
        self.actionExitApp.setIconText("Exit")
        self.actionExitApp.setToolTip("Exit (Alt + Q)")
        self.actionExitApp.setShortcut("Alt+Q")
        self.actionExitApp.setObjectName("actionExitApp")
        self.toolBar.addAction(self.actionNewText)
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSetting)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExitApp)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        
        # ####################################
        """Добавлено мною, не удалять!!!"""
        self.textcursor = QtGui.QTextCursor()

    def retranslateUi(self, MainForm):
        pass
